#!/bin/bash
config=$HOME/.config/
temas="$config/dotConfig/temas"
opcoes="apps\nbaixar\narea\naltab\nlogout\ntemas\natualizar"
#se $1 estiver vazio
if [ -z "$1" ]; then
	escolha=$(echo -e $opcoes | wofi -d --width=200 --height=150)
	if [ -z "$escolha" ]; then
		exit 0
	else	
		menus $escolha
	fi
fi
case "$1" in
	"apps")  
		wofi -S drun	
	;;
	"baixar")
		if [ -z "$2" ]; then
		tipo=$(echo -e "audio\nvideo" | wofi -d --width=200 --height=150 ) 
		else
		tipo=$2
		fi
		if [ -z "$3" ]; then
		url=$(cliphist list | wofi -d | cliphist decode)
		else
		url=$3
		fi
		if [ "$tipo" = "audio" ]; then
			cd ~/Músicas/
			yt-dlp -f 'bestaudio' --extract-audio --audio-format mp3 --embed-metadata "$url"
		fi
		if [ "$tipo" = "video" ]; then
			cd ~/Videos/
			yt-dlp -f 'bestvideo+bestaudio/bestvideo+bestaudio' --merge-output-format mp4 --embed-metadata "$url"
		fi
	;;
	"area")
		cliphist list | wofi -d --sort=default| cliphist decode | wl-copy
	;;
	"altab")
		titulo=$(hyprctl clients -j | jq '.[]' | jq -r '.title'| wofi -d)
		id=$(hyprctl clients -j | jq -r --arg titulo "$titulo" '.[] | select(.title | contains($titulo)) | .address')
		if [ -n "$id" ]; then
			out=$(hyprctl dispatch focuswindow "address:$id")
		fi
		notify-send -e "$(echo -e " Título:'$titulo'\nID:$id\n$out")" -h string:x-canonical-private-synchronous:pin -t 2000 -h string:transient:true 
	;;
	"logout")
		choice=$(echo -e "1: Desligar 󰐥\n2: Reiniciar 󰜉\n3: Sair 󰍃\n4: PS2 󰊖" | wofi -d --width=200 --height=150 | cut -d ':' -f 1)
		case "$choice" in
		  1) hyprctl dispatch exit & systemctl poweroff ;;
		  2) hyprctl dispatch exit & systemctl reboot ;;
		  3) hyprctl dispatch exit ;;
		  4) hyprctl dispatch exit & sh .bashrc 2 ;;
		esac
	;;
	"pin")
		titulo=$(hyprctl clients -j | jq '.[]' | jq -r '.title'| wofi -d)
		id=$(hyprctl clients -j | jq -r --arg titulo "$titulo" '.[] | select(.title | contains($titulo)) | .address')
		if [ -n "$id" ]; then
			hyprctl dispatch setfloating "address:$id"
			out=$(hyprctl dispatch pin "address:$id")
		fi
		notify-send -e "$(echo -e " Título:'$titulo'\nID:$id\n$out")" -h string:x-canonical-private-synchronous:pin -t 2000 -h string:transient:true 
	;;
	"temas")
		#se não tem algo em $2
		if [ -z "$2" ]; then
			cd $temas
			tema=$(ls -d */ | sed 's/\///g' | wofi -d --width=200 --height=200)
			#se não escolher tema
			if [ -z "$tema" ]; then
				exit 0
			fi
			menus $1 "$tema"
		fi
		#se tem algo em $2
		if [ -n "$2" ]; then
			cd $temas/$2
			ln -rsf * $config
			cp hypr/style.conf $config/hypr/
			killall waybar ; killall wpaperd ; killall swaync
			waybar & wpaperd -d & swaync
		fi
	;;
esac
