#!/bin/bash
indice=6
frases=( \
"Casas e riquezas herdam-se dos pais,\nmas a esposa prudente vem do Senhor.\n-Provérbios 19:14" \
"O pecado parece liberdade até você tentar parar" \
"Antes da morte qualquer derrota é psicológica" \
"Those who don't start today don't deserve a tommorow" \
"Those who cannot conceive friendship\nas a substantive love but only as a disguise\nor elaboration of eros betray the fact that\nthey have never had a friend." \
"When freedom is outlawed, only outlaws will be free!" \
"Seja caloroso ao demonstrar reconhecimento e pródigo nos elogios" \
)
max="${#frases[@]}" 
text=${frases[$indice]} 
printf "{ \"text\": \"%s\", \"tooltip\": \"%s\",}\n" \
       "$text" "$indice"
((indice++))
if [[ $indice -gt $max-1 ]]; then
	sed -i "2s/.*/indice=0/" "$0"
else
	sed -i "2s/.*/indice=$indice/" "$0"
fi
